### ISSUE TITLE
RDF List Import Error

### ISSUE THREAD

**Issue by blion-tec** [opensemanticsearch/open-semantic-search-appliance#10]
There's an error when trying to import thesaurus lists from rdf files/urls or SPARQL endpoints.
for example:
`
SELECT ?Mexico ?MexicoLabel WHERE {
	SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es". }
	?Mexico wdt:P17 wd:Q96.
}
limit 100
`

throws back this error:

> Request Method:  POST
> -- | --
> http://192.168.100.3/search-apps/ontologies/create
> 1.10.7
> FileNotFoundError
> [Errno 2] No such file or directory: '/**var/solr/data/core1/conf/named_entities/tmp_ocr_dictionary.txt**' -> '/etc/opensemanticsearch/ocr/dictionary.txt'
> /var/lib/opensemanticsearch/ontologies/views.py in write_named_entities_config, line 581
> /usr/bin/python3
> 3.5.3
> ['/var/lib/opensemanticsearch',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3/dist-packages/opensemanticetl',  '/']
> Tue, 27 Feb 2018 01:39:20 +0000

If **var/solr/data/core1/conf/named_entities/tmp_ocr_dictionary.txt** is touched and permissions are set to 0666 then it seems to work, but when apply ontology button is pressed the system throws this error:

> Request Method: | GET
> --  --
> http://192.168.100.3/search-apps/ontologies/1/apply
> 1.10.7
> AttributeError
> **'Document' object has no attribute 'serialize'**
> /var/lib/opensemanticsearch/ontologies/views.py in download_rdf_from_sparql_endpoint, line 153
> /usr/bin/python3
> 3.5.3
> ['/var/lib/opensemanticsearch',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3/dist-packages',  '/usr/lib/python3/dist-packages/opensemanticetl',  '/']
> Tue, 27 Feb 2018 01:59:56 +0000

**Comment by opensemanticsearch** [comment]
The SPAQL importer supports only RDF graphs or DESCRIBE and CONSTRUCT statements which return a RDF graph.

Support for SPARQL SELECT statements which return custom properties/fieldnames will be supported after implementation of https://github.com/opensemanticsearch/open-semantic-etl/issues/50

**Comment by Mandalka** [comment]
The SPARQL importer supports custom field names by SELECT statements now, will be added to Ontologies Manager UI for easier importing/filtering entities from triplestore by https://github.com/opensemanticsearch/open-semantic-search-apps/issues/21

**Comment by Mandalka** [comment]
Ontologies Manager now supports import of entities from custom fields / results of SPARQL SELECT statements, too.

Will be part of next open source release of packages.
