### ISSUE TITLE
Tika server returns status: 500

### ISSUE THREAD

**Issue by Quyrean** [opensemanticsearch/open-semantic-search-appliance#11]
I built the appliance from the latest sources.  I exported it to a virtual machine.  When I run  etl-file on the server I get an error

`etl-file -v -f /media/sf_searchme/test.txt`
```
2018-05-22 19:29:34,321 [MainThread  ] [WARNI]  Tika server returned status: 500
Exception while data enrichment of file:///searchme/test.txt with plugin enhance_extract_text_tika_server: 'content'
Exception while data enrichment of file:///searchme/test.txt with plugin enhance_pdf_ocr: 'content_type_ss'
Exception while data enrichment of file:///searchme/test.txt with plugin enhance_contenttype_group: 'content_type_ss'
Exception while data enrichment of file:///searchme/test.txt with plugin enhance_rdf_annotations_by_http_request: HTTP Error 500: Internal Server Error
Exception while data enrichment of file:///searchme/test.txt with plugin enhance_rdf: 'content_type_ss'
```

I know the tika server is running because I get a response when sending a request directly.

`curl -T /media/sf_searchme/test.txt http://localhost:9998/tika`

I changed the permission on the tika jar (not the link) to 777 and restarted the service.

I also tried running curl as tika user

![connect to tika as tika user](https://user-images.githubusercontent.com/30613311/40388539-72b1ed94-5dd5-11e8-87f9-5084c76f29f3.PNG)

here is the full log file

[etl-file.log](https://github.com/opensemanticsearch/open-semantic-search-appliance/files/2028468/etl-file.log)

Any ideas what is wrong or how to debug?  thanks.

**Comment by Mandalka** [comment]
If you build even the open semantic search and so the tika package from scratch:

Bug in Tika 1.18: https://github.com/opensemanticsearch/tika-server.deb/issues/7

Until then use Tika 1.17 too or go to config ui and set only one OCR dictionary.

Please reopen if not the solution.

**Comment by Quyrean** [comment]
Yes, that helped get me past that error, thanks.
