### ISSUE TITLE
spacy not running

### ISSUE THREAD

**Issue by Quyrean** [opensemanticsearch/open-semantic-search-appliance#12]
I built the packages myself, but it looks like spacy-services.deb is not being built correctly.  After running the deployed appliance I get the following error

```
root@debian:~# etl-file -f /media/sf_searchme/test.txt
Exception while data enrichment of file:///searchme/test.txt with plugin enhance_rdf_annotations_by_http_request: HTTP Error 500: Internal Server Error
Exception while data enrichment of file:///searchme/test.txt with plugin enhance_ner_spacy: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /ent (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb2cfee3240>: Failed to establish a new connection: [Errno 111] Connection refused',))
Forced indexing of unchanged file: /media/sf_searchme/test.txt

```

```
root@debian:~# ps auxwww | grep spacy
spacy      443  0.0  0.0  18712  1736 ?        S    20:37   0:00 daemon --user spacy --respawn --command python3 /usr/lib/python3/dist-packages/spacy-services/displacy/app.\
py --name=spacy --verbose
root      3535  0.0  0.0  12784   976 pts/1    S+   20:58   0:00 grep spacy
root@debian:~#
root@debian:~#
root@debian:~# python3 /usr/lib/python3/dist-packages/spacy-services/displacy/app.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spacy-services/displacy/app.py", line 4, in <module>
    import hug
ImportError: No module named 'hug'
root@debian:~# ls -l /usr/lib/python3/dist-packages/spacy-services/displacy/
total 12
-rw-r--r-- 1 root root 1867 May 21 19:19 app.py
-rw-r--r-- 1 root root 3620 May 21 19:19 README.md
-rw-r--r-- 1 root root 1060 May 21 19:19 requirements.txt
root@debian:~#


```

I built the spacy-services.deb package according to the instructions in the readme

```
##spacy-services.deb
cd spacy-services.deb/
mkdir -p src/
cd src
git clone https://github.com/explosion/spacy-services.git
cd ../build
sudo ./build
```
here is my repo

```
root@tailios:/home/user/repos/opensemanticsearch/spacy-services.deb# ls -lR src
src:
total 4
drwxr-xr-x 6 root root 4096 May 23 14:54 spacy-services

src/spacy-services:
total 20
drwxr-xr-x 2 root root 4096 May 23 14:54 displacy
-rw-r--r-- 1 root root 1103 May 23 14:54 LICENSE
drwxr-xr-x 2 root root 4096 May 23 14:54 matcher
-rw-r--r-- 1 root root 1150 May 23 14:54 README.md
drwxr-xr-x 2 root root 4096 May 23 14:54 sense2vec

src/spacy-services/displacy:
total 12
-rw-r--r-- 1 root root 1867 May 23 14:54 app.py
-rw-r--r-- 1 root root 3620 May 23 14:54 README.md
-rw-r--r-- 1 root root 1060 May 23 14:54 requirements.txt

src/spacy-services/matcher:
total 16
-rw-r--r-- 1 root root 1802 May 23 14:54 app.py
-rw-r--r-- 1 root root 5074 May 23 14:54 README.md
-rw-r--r-- 1 root root  232 May 23 14:54 requirements.txt

src/spacy-services/sense2vec:
total 12
-rw-r--r-- 1 root root 2764 May 23 14:54 app.py
-rw-r--r-- 1 root root 2583 May 23 14:54 README.md
-rw-r--r-- 1 root root  122 May 23 14:54 requirements.txt

```

any idea what I am doing wrong?

thanks.

**Comment by Mandalka** [comment]
Spacy services changed dependencies in newer releases. Now the spacy-services.deb package using the requirements.txt from spacy-services so all dependencies should be there automatically even if changes.

**Comment by dbsanfte** [comment]
I just ran into this on a fresh Ubuntu install after installing the .deb from the homepage.

Spacy service failing to start on bootup. Did a 'journalctl -xe' and found: "ImportError: No module named 'hug'"

Had to cd to /usr/lib/python3/dist-packages/spacy-services/displacy, do a pip3 install --upgrade pip, then pip3 install Cython, then pip3 install -r requirements.txt.

Then I could do a 'service spacy start' and it would work.

**Comment by melorium** [comment]
> mkdir -p src/

 src

**Comment by Man-Grove** [comment]
> I just ran into this on a fresh Ubuntu install after installing the .deb from the homepage.
> 
> Spacy service failing to start on bootup. Did a 'journalctl -xe' and found: "ImportError: No module named 'hug'"
> 
> Had to cd to /usr/lib/python3/dist-packages/spacy-services/displacy, do a pip3 install --upgrade pip, then pip3 install Cython, then pip3 install -r requirements.txt.
> 
> Then I could do a 'service spacy start' and it would work.

This happened to me too in a new install today, also from .deb in a completely fresh Debian 11, and the same solution worked for me too. Thanks @dbsanfte .

**Comment by Findarato** [comment]
I am trying this now with a fresh install on Debian 11 and still getting the hug error, after following @dbsanfte steps
