### ISSUE TITLE
Upgrade to Debian 10.7

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-appliance#18]

**Comment by Mandalka** [comment]
Fixed automount parameter for VBoxControl

**Comment by Mandalka** [comment]
Added dependency of package lsb-release, so workaround https://github.com/opensemanticsearch/open-semantic-search/issues/333 works on fresh Debian buster server (where this command not available like it is on a desktop installation f.e. of Open Semantic Desktop Search)
