### ISSUE TITLE
root/admin password?

### ISSUE THREAD

**Issue by hpiedcoq** [opensemanticsearch/open-semantic-search-appliance#2]
Hi!

I've downloaded the VM from here : 
https://www.jpberlin.de/www.opensemanticsearch.org/download/open-semantic-desktop-search_16.06.23.ova

But I need to install some stuff like tesseract in french. What's the root password of this VM?
My user is not admin.

Thanks.

**Comment by opensemanticsearch** [comment]
You mean the [git repository for Open Semantic Desktop Search](https://github.com/opensemanticsearch/open-semantic-desktop-search) (Search VM with GUI for single users), not this one of the search appliance VM (search server VM for teams), where the following infos were available yet in the documentation.

Thanks for your question and the info, that this informations were missing on the Desktop Search VM documentation, until the [user will get admin rights by sudo (opened an issue)](https://github.com/opensemanticsearch/open-semantic-desktop-search/issues/8).

I copied (and extended) the part of the [Desktop Search VM installation documentation](http://opensemanticsearch.org/doc/admin/install/desktop_search)

**Comment by hpiedcoq** [comment]
Thanks for the reply! Will try that!

**Comment by marciopula** [comment]
I have try to change to root user on Open Semantic Desktop Search and i cant.
Ask for a password and doesnt accept blank password.

I need to change Language to Portuguese for OCR.

Can you help me?

Thank You.
Márcio Rodrigues

**Comment by hpiedcoq** [comment]
Open a console (alt-F1 or ctrl-altf1) and logon as root without password to
open a new sessions.

It should work.




Le ven. 24 févr. 2017 à 01:46, marciopula <notifications@github.com> a
écrit :

**Comment by jacob-ogre** [comment]
Sorry to hit this closed issue, but I cannot for the life of me get the desktop search VM (downloaded this morning, 2017-04-02) running. Have read every page of documentation and I think every GH issue, but do not know the "debian login" and the "Password". Once in, the documentation is unclear as to the very basics of accessing the desktop search...

If I can get things working then I will be happy to help clarify the documentation, if that is of interest.

**Comment by cjpoor** [comment]
Hi. Thank you for developing SemanticSearch. It looks like it could be very useful.
However, I have the same problem regarding Admin/root password. Whether I log on with my regular user account or my administrator account, when I am presented with the dialog for "Insert Guest Additions" and I am asked for an Administrator password, no password that I know works. It also does not work to click "Authenticate" without entering anything as the password.

**Comment by phisqb** [comment]
I am having issues as well with the desktop virtualbox. If I bring up a terminal with ctrl-shift-F1, the username/password are: user/live

But "user" is not in the sudoers, so I can't copy the db.sqlite3 file anywhere that I can browse it to find out what the django admin password is. I have tried various combinations of user/live, admin/live, etc. but nothing works.

Does anyone know the Django admin username/password so I can setup some Facets?

I even tried to create a superuser within Django, but got an "unable to open database file" error.

**Comment by revolunet** [comment]
if you just `su` from the console as user, you're root :)

**Comment by Mandalka** [comment]
After upgrade to Debian 9 you can have root access by su from console/terminal within Gnome UI or with CTRL-right and F3 at once within the VM Linux system.

This is for installing packages / edit configs.

The admin access for Django/facet configs is done by
python3 manage.py createsuperuser
within the directory /var/lib/opensemanticsearch

**Comment by lalquier** [comment]
Since it took me a while to piece together this info from [other pages](https://www.opensemanticsearch.org/doc/admin/install/search_appliance) including this thread, here is what I had to do to be able to install the "Guest additions" in the VM:

1- bring up a console (from the Apps->Utilities since it seems more reliable than CTRL+F2 depending on your keyboard mappings)
2- type 'su' to switch to root access. No password necessary.
3- type 'passwd root' to change the Administrator password 

Once I did that, I was able to run the Guest addition install using the new password.

**Comment by m-lohmann** [comment]
> 2- type 'su' to switch to root access. No password necessary.

I’m using the VM, and this results in an authentication failure for me.
```
user@debian:~$ su
Password:                                           (I just hit the enter key)
su: Authentication failure

```

**Comment by jafoool** [comment]
Hi, I got the same pb here : authentifcation failure on Su, trying as stated : no password, live ...

**Comment by Mandalka** [comment]
Debian 10 changed the default key commands for change to console.

I updated part "Root access" in documentation https://opensemanticsearch.org/doc/admin/install/desktop_search

su (is yet not working until you set a root password like described in this documentation).

**Comment by Chaddhaji** [comment]
For Debian 10.0
CTRL(right-side) + F3
Login as root without password. | it will not ask password here
```
passwd root
live
```
Password reset
CTRL(right-side) + F2 | go back

**Comment by mr5proper** [comment]
I'm using Virtual Box and Open Semantic Desktop Search on **IMac**.
Changing root password :

1. In Open Semantic Desktop open Console by pressing 
strg + alt + F6    (**iMac Keyboard**)

2. Login as root without any password

3. Set password for root:
$ passwd

4. Restart Debian

**Comment by StephenRKraemer** [comment]
Another option to change the root password (and hence the Administrator password) is to start the Virtual Box Open Semantic Desktop in GNU Recovery Mode and let it boot into command line.  Login as root (no password).  At command line type "passwd" and change the root password as desired.  Then exit the session and the recovery mode, and the VM Guest should login to the GUI.  Once in the GUI, run Virtual Box Guest Additions.  When prompted for Administrator password, type in the password given earlier to root.  Should be good to go.   

If after exiting recovery mode the Guest does not revert to GUI, then simply restart the Guest.
