### ISSUE TITLE
Upgrade to Debian 9

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-appliance#7]
Upgrade to / base on new stable release Debian 9 stretch and new(est) version of Open Semantic Search

**Comment by opensemanticsearch** [comment]
Need to automate installation of Virtual Box guest additions while build, since VM guest additions not standard Debian package anymore.

Maybe a client will order this option instead of Docker integration, so it could be done in ~two weeks before other projects.

**Comment by Mandalka** [comment]
VM now based on Debian 9, Python 3 and Open Semantic Search is installed automatically within the running VM with its full environment.
