### ISSUE TITLE
network configuration

### ISSUE THREAD

**Issue by trenkert** [opensemanticsearch/open-semantic-search-appliance#9]
![image](https://user-images.githubusercontent.com/143727/33926462-8b434c1a-dfde-11e7-9e97-980e87117864.png)

this part of the documentation is a bit confusing. What should the VM settings be? NAT? bridged? Do I need to set a static IP in the VM? 

If I enter the IP + port of the VM in my host browser nothing happens, the page is stuck mid-loading...

**Comment by opensemanticsearch** [comment]
Your users have to get access to the ip of the host server and to the hosts port that is configured in vm settings under extended network settings / portforwarding as host port (let the ips on 0.0.0.0 so the hosts ip and guest ip is used automatically). the client port in this setting has to be set to 80. You can set the host port to 80, too if the host has no other webserver running and so blocking this port.
